# Generated by Django 4.1.5 on 2023-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_post_change_news_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='change_news',
            field=models.CharField(choices=[('NE', 'News'), ('AR', 'Article')], default='AR', help_text='change news', max_length=2),
        ),
    ]
