# Generated by Django 4.1.5 on 2023-02-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_change_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_en_us',
            field=models.ManyToManyField(help_text='Category', null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_es_ar',
            field=models.ManyToManyField(help_text='Category', null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru_ru',
            field=models.ManyToManyField(help_text='Category', null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='change_news_en_us',
            field=models.CharField(choices=[('NE', 'News'), ('AR', 'Article')], default='AR', help_text='change news', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='change_news_es_ar',
            field=models.CharField(choices=[('NE', 'News'), ('AR', 'Article')], default='AR', help_text='change news', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='change_news_ru_ru',
            field=models.CharField(choices=[('NE', 'News'), ('AR', 'Article')], default='AR', help_text='change news', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rate_news_en_us',
            field=models.SmallIntegerField(default=0, help_text='rate news', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rate_news_es_ar',
            field=models.SmallIntegerField(default=0, help_text='rate news', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rate_news_ru_ru',
            field=models.SmallIntegerField(default=0, help_text='rate news', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_in_en_us',
            field=models.DateTimeField(auto_now_add=True, help_text='time in', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_in_es_ar',
            field=models.DateTimeField(auto_now_add=True, help_text='time in', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_in_ru_ru',
            field=models.DateTimeField(auto_now_add=True, help_text='time in', null=True),
        ),
        migrations.CreateModel(
            name='PostCategory_ru_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(help_text='post', on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [ru-ru]',
                'verbose_name_plural': 'post categorys [ru-ru]',
                'db_table': 'news_postcategory_ru_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_es_ar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(help_text='post', on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [es-ar]',
                'verbose_name_plural': 'post categorys [es-ar]',
                'db_table': 'news_postcategory_es_ar',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(help_text='category', on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(help_text='post', on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'post category [en-us]',
                'verbose_name_plural': 'post categorys [en-us]',
                'db_table': 'news_postcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
