# Generated by Django 4.1.5 on 2023-02-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_category_en_us_post_category_es_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='change_news_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='change_news_es_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='change_news_ru_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rate_news_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rate_news_es_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rate_news_ru_ru',
        ),
    ]
